### ISSUE TITLE
Some Qarcoal tests failing on Travis

### ISSUE THREAD

**Issue by gibsramen** [biocore/qurro#271] opened 2020-02-15 01:14 UTC
Recently pushed to a [local branch](https://github.com/gibsramen/qurro/commit/20f8582bfc433ffbc50cba149966a3c6028c3e79) that shouldn't interfere with any of the main Qurro code. [Travis build](https://travis-ci.org/gibsramen/qurro/builds/650680331?utm_source=github_status&utm_medium=notification) fails on some of the Qarcoal tests:

- TestIrregularData.test_taxon_as_sample_name
- TestIrregularData.test_feat_table_missing_features
- TestIrregularData.test_taxonomy_missing_features
- TestErrors.test_no_common_samples

Possibly related to the `biom` update @antgonza mentioned? Looks like the build is using the new `biom-format 2.1.8`.

I had some problems with converting `biom` to `DataFrame` earlier today that I *think* were caused by an errant column name.

**Comment by fedarko** [comment] 2020-02-15 04:21
Oof, perfect timing :P I think pinning biom to `biom-format[hdf5]>=2.1.8.post1` in the setup.py might work to resolve this -- could you try that and see if it un-breaks this?

A side effect of moving to biom 2.1.8 is that [it drops support for python 3.5](https://github.com/biocore/biom-format/releases), so we'll have to handle that. opening an issue for that in #272.

**Comment by gibsramen** [comment] 2020-02-18 21:35
Pinning `biom` causes `qiime dev refresh-cache` to fail. May be an interaction with `pandas 1.0.0` and `biom-format 2.1.8`.

[Travis build](https://travis-ci.org/gibsramen/qurro/builds/652181983?utm_source=github_status&utm_medium=notification)

**Comment by gibsramen** [comment] 2020-02-18 22:24
Looking specifically at `test_qarcoal.py::test_taxon_as_sample_name`

![image](https://user-images.githubusercontent.com/4030868/74783291-394b6c80-525a-11ea-8b57-3c4c1e6af8c2.png)

The values are still the same (good!) but the data structures have diverged.

**Comment by fedarko** [comment] 2020-02-18 22:35
Oh, huh. looks like the problem is that the "fill value" for the sparse data structure is different -- IIRC it's NaN by default in pandas, and we finagle it to be 0 in most of Qurro.

Guessing that it's an inconsistency between the Qarcoal test code and the actual Qarcoal code -- they're probably using slightly differently initialized data structures? Maybe one was relying on some sort of default behavior that a new Pandas / etc. version has changed.

def related to #258

**Closed** 2020-02-25 20:56 UTC
Labels: external, qarcoal
